#!/bin/bash

clear

current_dir=$(pwd)
patch_dir="$current_dir/patches"
output_dir="$current_dir/new/" # TODO: remove this in favor of $game_path


echo -n "Location of ETS2: "
read game_path
echo "$game_path"

# check if patch_dir and output_dir exist
if [[ ! -d $patch_dir ]]
then
    mkdir $patch_dir
fi

if [[ ! -d $output_dir ]]
then
    mkdir $output_dir
fi

IFS=$'\n'

for file in $(find $patch_dir -name '*.xdelta')
do
    filename=$(basename $file)
    extension="${filename##*.}"
    filename_new="${filename%.*}"

    if [[ -n $(find $game_path -name $filename_new) ]]
    then
        old_path=$(find $game_path -name $filename_new)
        echo "Patching $filename_new"
        xdelta3 -d -f -s "$old_path" "$file" "$output_dir/$filename_new"
    else # file doesn't exist in old version
        echo "Error: Can't find $filename_new"
    fi
done